<%@ page pageEncoding="UTF-8" %>
<%@ include file="../layouts/shop-start.jspf" %>
<div class="chat-page-heading"><div><p class="eyebrow">MUA BÁN BẮT ĐẦU TỪ KẾT NỐI</p><h1>Tin nhắn của bạn</h1><p>Hỏi một chút, hiểu món đồ hơn.</p></div><a class="button secondary" href="<c:url value='/products' />">Khám phá sản phẩm ↗</a></div>
<div class="chat-workspace ${empty conversation ? '' : 'has-thread'}" data-chat data-context="${pageContext.request.contextPath}" data-conversation="<c:out value='${conversation.id}' />" data-csrf="<c:out value='${csrfToken}' />">
<aside class="chat-inbox" aria-label="Cuộc trò chuyện"><div class="chat-list-heading"><h2>Hộp thư</h2><span class="chat-connection" data-chat-connection role="status">Đang tải cập nhật…</span></div><div class="chat-conversations" data-chat-list>
<c:forEach var="thread" items="${conversations}"><a class="chat-preview ${thread.id == conversation.id ? 'is-selected' : ''}" data-chat-id="${thread.id}" href="<c:url value='/messages'><c:param name='id' value='${thread.id}' /></c:url>" ${thread.id == conversation.id ? 'aria-current="page"' : ''}><img src="<c:url value='${thread.imagePath}' />" alt=""><span class="chat-preview-copy"><span class="chat-preview-top"><strong><c:out value="${thread.otherName}" /></strong><c:if test="${thread.unread > 0}"><span class="chat-count" aria-label="Tin chưa đọc"><c:out value="${thread.unread}" /></span></c:if></span><span class="chat-preview-title"><c:out value="${thread.title}" /></span><span class="chat-preview-body"><c:out value="${empty thread.lastBody ? 'Chưa có tin nhắn · Hãy chào nhau!' : thread.lastBody}" /></span><time><c:out value="${thread.when}" /></time></span></a></c:forEach>
<c:if test="${empty conversations}"><div class="chat-list-empty"><span aria-hidden="true">✉</span><strong>Hộp thư đang trống</strong><p>Chọn “Chat với người bán” tại một sản phẩm để bắt đầu.</p></div></c:if></div></aside>
<section class="chat-thread" aria-label="Nội dung trò chuyện">
<c:choose><c:when test="${empty conversation}"><div class="chat-welcome"><span class="chat-symbol" aria-hidden="true">✉</span><p class="eyebrow">MỘT LỜI CHÀO, THÊM MỘT KẾT NỐI</p><h2>Chọn một cuộc trò chuyện</h2><p>Hỏi về món đồ, thống nhất cách nhận hàng<br>và lưu lại trao đổi ở đây.</p><a class="button" href="<c:url value='/products' />">Tìm món đồ yêu thích</a></div></c:when><c:otherwise>
<header class="chat-thread-heading"><a class="chat-back" href="<c:url value='/messages' />" aria-label="Quay về hộp thư">←</a><span class="chat-avatar" aria-hidden="true">↗</span><div><h2><c:out value="${conversation.otherName}" /></h2><span>Trao đổi riêng giữa hai người tham gia</span></div></header>
<p class="seller-approved chat-seller-verified" data-chat-verification title="Giấy tờ trong hồ sơ đã được quản trị viên kiểm tra" ${conversation.sellerVerified ? '' : 'hidden'}><svg class="icon" aria-hidden="true"><use href="#i-shield" /></svg>Đã xác minh hồ sơ</p><div class="chat-product"><img data-chat-product-image src="<c:url value='${conversation.imagePath}' />" alt=""><div><span class="eyebrow">SẢN PHẨM ĐANG TRAO ĐỔI</span><strong data-chat-product-title><c:out value="${conversation.title}" /></strong><span data-chat-product-state>${conversation.available ? 'Đang được công khai' : 'Tin không còn công khai · Lịch sử vẫn được giữ'}</span></div><a data-chat-product-link href="<c:url value='${conversation.productPath}' />" ${conversation.available ? '' : 'hidden'}>Xem sản phẩm ↗</a></div>
<div class="chat-history" data-chat-history tabindex="0" aria-label="Lịch sử tin nhắn"><button type="button" class="chat-load-older secondary" data-chat-older ${more ? '' : 'hidden'}>Xem tin nhắn trước</button><p class="chat-start-note">Trao đổi về sản phẩm tại đây. Hãy giữ thông tin cá nhân của bạn an toàn.</p><div data-chat-messages>
<c:forEach var="message" items="${messages}"><div class="chat-message ${message.mine ? 'is-mine' : ''}" data-message-id="${message.id}"><p><c:out value="${message.body}" /></p><time><c:out value="${message.sentAt}" /></time></div></c:forEach></div><p class="chat-no-messages" data-chat-empty ${empty messages ? '' : 'hidden'}>Chưa có tin nhắn. Gửi lời chào đầu tiên nhé!</p></div>
<button type="button" class="chat-new secondary" data-chat-new hidden>↓ Có tin mới · Xem ngay</button>
<form class="chat-composer" data-chat-form method="post" action="<c:url value='/messages/send' />"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="conversationId" value="${conversation.id}"><input type="hidden" name="nonce" value="<c:out value='${sendNonce}' />"><label class="sr-only" for="chat-body">Nội dung tin nhắn</label><textarea id="chat-body" name="body" rows="2" maxlength="2000" required placeholder="Nhắn một lời chào hoặc hỏi về sản phẩm…" ${conversation.canSend ? '' : 'disabled'}><c:out value="${draft}" /></textarea><button type="submit" ${conversation.canSend ? '' : 'disabled'}>Gửi <span aria-hidden="true">↗</span></button><div class="chat-compose-meta"><span data-chat-send-status role="status"><c:out value="${chatError}" />${param.notice == 'sent' ? 'Đã gửi tin nhắn.' : ''}<c:if test="${not conversation.canSend}">Người còn lại đã ngừng hoạt động; bạn vẫn xem được lịch sử.</c:if></span><span><span data-chat-length>0</span>/2.000</span></div></form>
<noscript><form method="post" action="<c:url value='/messages/read' />"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="conversationId" value="${conversation.id}"><input type="hidden" name="through" value="${empty messages ? 0 : messages[fn:length(messages)-1].id}"><button class="secondary">Đánh dấu đã đọc</button></form><p>Tải lại trang để xem tin mới khi JavaScript bị tắt.</p></noscript>
</c:otherwise></c:choose></section></div>
<%@ include file="../layouts/shop-end.jspf" %>
