<%@ page pageEncoding="UTF-8" %>
<%@ include file="../layouts/shop-start.jspf" %>
<h1><c:out value="${empty product ? 'Đăng sản phẩm' : 'Sửa sản phẩm'}" /></h1><p><a href="<c:url value='${manageBase}' />">← Danh sách sản phẩm</a></p>
<c:if test="${not empty formError}"><p class="error" role="alert"><c:out value="${formError}" /></p></c:if>
<c:url var="saveUrl" value="${manageBase}/save" />
<section><form method="post" enctype="multipart/form-data" action="${saveUrl}" class="account-form">
<input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="id" value="${empty product ? 0 : product.id}"><input type="hidden" name="listingVersion" value="<c:out value='${posted ? param.listingVersion : (empty product ? 0 : product.listing_version)}' />"><input type="hidden" name="stockVersion" value="<c:out value='${posted ? param.stockVersion : (empty product ? 0 : product.stock_version)}' />">
<c:if test="${adminMode && empty product}"><label>Người bán sở hữu sản phẩm<select name="sellerId" required><option value="">Chọn người bán</option><c:forEach var="seller" items="${sellers}"><option value="${seller.id}" ${param.sellerId == seller.id.toString() ? 'selected' : ''}><c:out value="${seller.display_name}" /> (#${seller.id})</option></c:forEach></select></label></c:if>
<h2 class="form-section-title">1. Thông tin sản phẩm</h2><label>Tên sản phẩm<input name="title" required minlength="2" maxlength="200" value="<c:out value='${posted ? param.title : product.title}' />"></label>
<label>Danh mục<select name="categoryId" required><option value="">Chọn danh mục</option><c:forEach var="category" items="${categories}"><option value="${category.id}" ${(posted ? param.categoryId : product.category_id) == category.id.toString() ? 'selected' : ''}><c:out value="${category.name}" /></option></c:forEach></select></label>
<label>Mô tả<textarea name="description" rows="6" required maxlength="10000"><c:out value="${posted ? param.description : product.description}" /></textarea></label>
<h2 class="form-section-title">2. Giá và số lượng</h2><div class="form-row"><label>Giá (đồng)<input name="price" type="number" min="1" max="999999999999" step="1" required value="<c:out value='${posted ? param.price : product.price}' />"></label><label>Số lượng còn bán<input name="stock" type="number" min="0" max="1000000" required value="<c:out value='${posted ? param.stock : (empty product ? 1 : product.stock_quantity)}' />"></label></div>
<label>Tình trạng<select name="condition"><c:forEach var="condition" items="${['NEW','LIKE_NEW','USED']}"><option value="${condition}" ${(posted ? param.condition : product.condition_code) == condition ? 'selected' : ''}><c:out value="${labels[condition]}" /></option></c:forEach></select></label>
<label>Chế độ hiển thị<select name="visibility"><option value="PUBLIC" ${(posted ? param.visibility : product.visibility) == 'PUBLIC' ? 'selected' : ''}>Công khai sau khi được duyệt</option><option value="HIDDEN" ${(posted ? param.visibility : product.visibility) == 'HIDDEN' ? 'selected' : ''}>Ẩn</option></select></label>
<%@ include file="condition-form.jspf" %>
<h2 class="form-section-title">4. Hình ảnh và đăng tin</h2><label>Ảnh sản phẩm (tối đa 5 ảnh JPEG/PNG, 5 MB mỗi ảnh)<input name="photos" data-photo-picker="5" data-defect-picker type="file" accept="image/jpeg,image/png" multiple></label><small>Không chọn ảnh: giữ ảnh hiện có. Chọn ảnh mới: thay toàn bộ ảnh tin. Nếu thiếu ảnh sẽ dùng ảnh mặc định.</small>
<c:if test="${not empty images}"><p class="condition-note">Đánh dấu ảnh khuyết điểm hiện có (khi giữ bộ ảnh):</p><div class="defect-choices"><c:forEach var="image" items="${images}"><label class="defect-choice"><input type="checkbox" name="defectAsset" value="${image.asset_id}" ${image.is_defect ? 'checked' : ''}><img src="<c:url value='/media/product'><c:param name='asset' value='${image.asset_id}' /></c:url>" alt="Ảnh hiện có">Ảnh khuyết điểm</label></c:forEach></div></c:if>
<label>Lý do điều chỉnh / xử lý<textarea name="reason" maxlength="500" rows="2" ${currentUser.admin ? 'required' : ''}><c:out value="${param.reason}" /></textarea></label><small>Bắt buộc khi đổi số lượng hoặc Admin thao tác. Số lượng 0 hiển thị hết hàng; sửa nội dung/giá/ảnh sẽ chờ duyệt lại.</small>
<button>Lưu sản phẩm</button></form>
</section>
<%@ include file="../layouts/shop-end.jspf" %>
