<%@ page pageEncoding="UTF-8" %><%@ include file="../layouts/shop-start.jspf" %>
<div class="page-heading"><div><p class="eyebrow">Những món bạn đã chọn</p><h1>Giỏ hàng</h1></div><a href="<c:url value='/products' />">← Tiếp tục mua sắm</a></div>
<div data-cart data-cart-url="<c:url value='/cart' />">
<div class="cart-feedback" data-cart-feedback hidden><p data-cart-status role="status"></p><button type="button" class="secondary" data-cart-refresh hidden>Kiểm tra lại giỏ hàng</button><a class="button secondary" href="<c:url value='/cart' />" data-cart-reload hidden>Tải lại giỏ hàng</a></div>
<section class="empty-state" data-cart-empty ${empty cart.items ? '' : 'hidden'}><h2>Giỏ hàng của bạn đang trống</h2><p>Khám phá sản phẩm và thêm những món bạn thích vào đây.</p><a class="button" href="<c:url value='/products' />">Khám phá sản phẩm</a></section>
<div class="cart-layout" data-cart-layout ${empty cart.items ? 'hidden' : ''}><div><c:forEach var="p" items="${cart.items}"><section class="cart-item" data-cart-item data-product-id="${p.id}" data-can-change="${p.can_change_quantity}">
<c:choose><c:when test="${not empty p.image_id}"><c:url var="imageUrl" value="/media/product"><c:param name="asset" value="${p.image_id}" /></c:url><img src="${imageUrl}" alt="<c:out value='${p.title}' />"></c:when><c:otherwise><img src="<c:url value='/assets/images/product-placeholder.svg' />" alt="Người bán chưa thêm ảnh"></c:otherwise></c:choose>
<div><c:url var="cartProductUrl" value="/products/detail"><c:param name="id" value="${p.id}" /></c:url><h2><a href="${cartProductUrl}"><c:out value="${p.title}" /></a></h2><p class="muted">Người bán: <c:out value="${p.seller_name}" /></p><p><span data-cart-unit-price><fmt:formatNumber value="${p.price}" pattern="#,##0" /> ₫</span> × <span data-cart-count>${p.quantity}</span></p><strong class="price" data-cart-line-total><fmt:formatNumber value="${p.line_total}" pattern="#,##0" /> ₫</strong><p class="error" data-cart-unavailable ${p.available ? 'hidden' : ''}>Sản phẩm không còn đủ điều kiện mua. Điều chỉnh số lượng hoặc xóa khỏi giỏ.</p></div>
<div class="cart-controls"><form method="post" action="<c:url value='/cart/update' />" data-cart-quantity-form><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="productId" value="${p.id}"><div class="cart-stepper"><button type="submit" name="adjust" value="-1" class="secondary" data-cart-step="-1" aria-label="Giảm số lượng" ${!p.can_change_quantity or p.quantity <= 1 ? 'disabled' : ''}>−</button><input type="number" name="quantity" aria-label="Số lượng" value="${p.quantity}" data-cart-quantity data-confirmed-quantity="${p.quantity}" data-max-quantity="${p.max_quantity}" min="1" max="999" step="1" required ${p.can_change_quantity ? '' : 'disabled'}><button type="submit" name="adjust" value="1" class="secondary" data-cart-step="1" aria-label="Tăng số lượng" ${!p.can_change_quantity or p.quantity >= p.max_quantity ? 'disabled' : ''}>+</button></div></form><form method="post" action="<c:url value='/cart/remove' />" data-cart-remove><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="productId" value="${p.id}"><button class="secondary">Xóa khỏi giỏ</button></form></div></section></c:forEach></div>
<section class="cart-summary"><h2>Tóm tắt giỏ hàng</h2><div class="summary-line"><span>Tiền sản phẩm</span><span data-cart-total><fmt:formatNumber value="${cart.total}" pattern="#,##0" /> ₫</span></div><div class="summary-line"><span>Phí vận chuyển demo</span><span>0 ₫</span></div><div class="summary-line total"><strong>Tổng tiền</strong><strong class="price" data-cart-total><fmt:formatNumber value="${cart.total}" pattern="#,##0" /> ₫</strong></div><a class="button cart-checkout" data-cart-checkout href="<c:url value='/checkout' />">Tiến hành đặt hàng →</a><small>Giá và tồn kho được kiểm tra lại khi đặt hàng. Mỗi người bán có một đơn riêng.</small></section></div>
</div><%@ include file="../layouts/shop-end.jspf" %>
