<%@ page pageEncoding="UTF-8" %>
<%@ include file="../layouts/shop-start.jspf" %>
<div class="steps"><span>1. Giỏ hàng</span><span>→</span><span class="current">2. Đặt hàng</span><span>→</span><span>3. Hoàn tất</span></div><h1>Xác nhận đặt hàng</h1><p><a href="<c:url value='/cart' />">← Xem lại giỏ hàng</a></p><c:if test="${not empty formError}"><p class="error" role="alert"><c:out value="${formError}" /></p></c:if>
<c:choose><c:when test="${empty cart.items}"><section><h2>Giỏ hàng đang trống</h2><a class="button" href="<c:url value='/products' />">Tiếp tục mua sắm</a></section></c:when><c:otherwise>
<div class="checkout-layout"><section><h2>Thông tin nhận hàng</h2><form method="post" action="<c:url value='/checkout' />" class="account-form"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="key" value="${checkoutKey}"><input type="hidden" name="quote" value="${cart.quote}">
<label>Tên người nhận<input name="name" minlength="2" maxlength="100" required autocomplete="name" value="<c:out value='${param.name}' />"></label><label>Điện thoại<input name="phone" type="tel" maxlength="16" required autocomplete="tel" value="<c:out value='${param.phone}' />"></label><label>Địa chỉ nhận hàng<textarea name="address" minlength="10" maxlength="500" required autocomplete="street-address"><c:out value="${param.address}" /></textarea></label><label>Ghi chú (tùy chọn)<textarea name="note" maxlength="1000"><c:out value="${param.note}" /></textarea></label>
<label>Thanh toán<select name="method"><option value="COD">Thanh toán khi nhận hàng (COD)</option><option value="VNPAY_SANDBOX" ${param.method == 'VNPAY_SANDBOX' ? 'selected' : ''}>VNPAY Sandbox – môi trường thử nghiệm</option></select></label><p class="notice">COD: thanh toán khi nhận hàng. VNPAY Sandbox: dùng thẻ thử nghiệm, không chuyển tiền thật. Mỗi người bán có một đơn và một giao dịch thanh toán riêng.</p><button>Đặt hàng — <fmt:formatNumber value="${cart.total}" pattern="#,##0" /> ₫</button></form></section>
<section class="checkout-summary"><h2>Đơn hàng của bạn</h2><c:forEach var="p" items="${cart.items}"><div class="checkout-product"><c:choose><c:when test="${not empty p.image_id}"><c:url var="checkoutImage" value="/media/product"><c:param name="asset" value="${p.image_id}" /></c:url><img class="thumbnail" src="${checkoutImage}" alt="Ảnh sản phẩm"></c:when><c:otherwise><img class="thumbnail" src="<c:url value='/assets/images/product-placeholder.svg' />" alt="Chưa có ảnh"></c:otherwise></c:choose><p><strong><c:out value="${p.title}" /></strong> × ${p.quantity}<br><small>Người bán: <c:out value="${p.seller_name}" /></small><br><fmt:formatNumber value="${p.line_total}" pattern="#,##0" /> ₫</p><c:if test="${!p.available}"><p class="error">Không còn đủ điều kiện mua.</p></c:if></div></c:forEach><hr><p>Phí vận chuyển: 0 ₫</p><p class="price">Tổng: <fmt:formatNumber value="${cart.total}" pattern="#,##0" /> ₫</p></section></div>
</c:otherwise></c:choose><%@ include file="../layouts/shop-end.jspf" %>
