<%@ page pageEncoding="UTF-8" %>
<%@ include file="../layouts/shop-start.jspf" %>
<section class="account-card"><p class="eyebrow">Chia sẻ trải nghiệm mua hàng</p><h1>Đánh giá sản phẩm</h1><a href="<c:url value='/buyer/orders/detail'><c:param name='id' value='${order.id}' /></c:url>">← Về đơn hàng</a>
<div class="review-item-summary"><c:set var="reviewThumbnail" value="false" /><c:forEach items="${snapshotImages}" var="pic"><c:if test="${pic.order_item_id == item.id and not reviewThumbnail}"><c:set var="reviewThumbnail" value="true" /><img src="<c:url value='/media/order-image'><c:param name='orderId' value='${order.id}' /><c:param name='asset' value='${pic.asset_id}' /></c:url>" alt="Sản phẩm khi đặt hàng"></c:if></c:forEach><c:if test="${not reviewThumbnail}"><img src="<c:url value='/assets/images/product-placeholder.svg' />" alt="Chưa có ảnh"></c:if><div><strong><c:out value="${item.product_name_snapshot}" /></strong><p><c:out value="${labels[item.condition_snapshot]}" /> · <fmt:formatNumber value="${item.unit_price}" maxFractionDigits="0" /> ₫</p><span class="verified-badge">✓ Đã mua qua hệ thống</span></div></div>
<c:if test="${not empty formError}"><p class="error" role="alert"><c:out value="${formError}" /></p></c:if>
<c:choose><c:when test="${not empty review}"><p class="notice">Bạn đã đánh giá sản phẩm này: ${review.product_rating}/5 sao.</p><p class="preserve"><c:out value="${review.comment}" /></p></c:when><c:otherwise>
<form class="account-form" method="post" enctype="multipart/form-data" action="<c:url value='/buyer/reviews/create' />"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="orderId" value="${order.id}"><input type="hidden" name="itemId" value="${item.id}">
<fieldset><legend>Bạn hài lòng như thế nào?</legend><div class="star-rating"><c:forEach begin="1" end="5" var="star"><label class="star-option"><input type="radio" name="rating" value="${star}" required ${param.rating == star.toString() ? 'checked' : ''}><span>★<small>${star} sao</small></span></label></c:forEach></div></fieldset>
<label>Nhận xét<textarea name="comment" rows="5" maxlength="2000" required placeholder="Sản phẩm có đúng mô tả? Trải nghiệm trao đổi với người bán ra sao?"><c:out value="${param.comment}" /></textarea></label>
<label>Ảnh thực tế (không bắt buộc)<input type="file" name="photos" data-photo-picker="3" multiple accept="image/jpeg,image/png"></label><small>Tối đa 3 ảnh JPEG/PNG, 5 MB mỗi ảnh. Bạn có thể bỏ ảnh trong phần xem trước. Khi gửi lỗi, vui lòng chọn lại ảnh.</small><button>Gửi đánh giá</button></form>
</c:otherwise></c:choose></section>
<%@ include file="../layouts/shop-end.jspf" %>
