<%@ page pageEncoding="UTF-8" %>
<%@ include file="../layouts/shop-start.jspf" %>
<div class="feature-heading"><div><p class="eyebrow">Chọn món đồ phù hợp với bạn</p><h1>So sánh sản phẩm</h1><p>Đối chiếu giá và tình trạng do người bán khai báo. Thông tin được lấy từ tin đăng hiện tại.</p></div><span class="feature-icon" aria-hidden="true">⇄</span></div>
<c:if test="${not empty unavailableIds}"><section class="compare-invalid"><h2>Một số sản phẩm không còn được hiển thị</h2><p>Hãy bỏ khỏi danh sách và chọn sản phẩm khác.</p><c:forEach items="${unavailableIds}" var="id"><button class="secondary" type="button" data-remove-compare="${id}">Bỏ sản phẩm #${id}</button></c:forEach></section></c:if>
<c:choose><c:when test="${fn:length(comparedProducts) < 2 or not sameCategory}"><section class="compare-empty"><h2>${sameCategory ? 'Chọn ít nhất 2 sản phẩm' : 'Chọn các sản phẩm cùng danh mục'}</h2><p>Tối đa 3 sản phẩm để dễ theo dõi các khác biệt.</p><a class="button" href="<c:url value='/products' />">Khám phá sản phẩm</a><div class="actions"><c:forEach items="${comparedProducts}" var="p"><button class="secondary" type="button" data-remove-compare="${p.id}">Bỏ <c:out value="${p.title}" /></button></c:forEach></div></section></c:when><c:otherwise>
<div class="compare-options"><label><input type="checkbox" data-only-different> Chỉ hiện điểm khác nhau</label><a href="<c:url value='/products' />">+ Chọn sản phẩm khác</a></div>
<div class="compare-scroll"><table class="compare-table"><thead><tr><th scope="col">Tiêu chí</th><c:forEach items="${comparedProducts}" var="p"><th class="compare-product" scope="col"><button class="secondary" type="button" data-remove-compare="${p.id}" aria-label="Bỏ sản phẩm">× Bỏ chọn</button><c:choose><c:when test="${not empty p.image_id}"><img src="<c:url value='/media/product'><c:param name='asset' value='${p.image_id}' /></c:url>" alt="<c:out value='${p.title}' />"></c:when><c:otherwise><img src="<c:url value='/assets/images/product-placeholder.svg' />" alt="Chưa có ảnh"></c:otherwise></c:choose><h2><c:out value="${p.title}" /></h2><small><c:out value="${p.category_name}" /></small></th></c:forEach></tr></thead><tbody>
<c:forEach items="${comparisonRows}" var="row"><tr data-different="${row.different}"><th scope="row"><c:out value="${row.label}" /></th><c:forEach items="${comparedProducts}" var="p"><td class="preserve ${row.key == 'price' and p.price == lowestPrice ? 'lowest-price' : ''}"><c:choose><c:when test="${row.key == 'price'}"><fmt:formatNumber value="${p.price}" maxFractionDigits="0" /> ₫<c:if test="${p.price == lowestPrice}"><span class="lowest-label">Giá thấp nhất trong lựa chọn</span></c:if></c:when><c:when test="${row.key == 'seller_rating'}"><c:choose><c:when test="${p.seller_review_count > 0}"><fmt:formatNumber value="${p.seller_rating}" maxFractionDigits="1" /> / 5 ★<small> · ${p.seller_review_count} đánh giá</small></c:when><c:otherwise>Chưa có đánh giá</c:otherwise></c:choose></c:when><c:when test="${row.key == 'condition_code'}"><c:out value="${labels[p[row.key]]}" default="Chưa cung cấp" /></c:when><c:when test="${row.key == 'appearance_code' or row.key == 'operation_code' or row.key == 'repair_code'}"><c:out value="${conditionLabels[p[row.key]]}" default="Chưa cung cấp" /></c:when><c:otherwise><c:out value="${p[row.key]}" default="Chưa cung cấp" /></c:otherwise></c:choose></td></c:forEach></tr></c:forEach>
<tr><th scope="row">Trao đổi &amp; mua</th><c:forEach items="${comparedProducts}" var="p"><td><div class="comparison-actions"><a class="button secondary" href="<c:url value='/products/detail'><c:param name='id' value='${p.id}' /></c:url>">Xem chi tiết</a>
<c:choose><c:when test="${empty currentUser}"><a href="<c:url value='/login' />">Đăng nhập để mua</a><a href="<c:url value='/messages/start'><c:param name='productId' value='${p.id}' /></c:url>">✉ Chat với người bán</a></c:when><c:when test="${currentUser.id == p.seller_id}"><small>Sản phẩm của bạn</small></c:when><c:otherwise><c:if test="${p.stock_quantity > 0}"><form method="post" action="<c:url value='/cart/add' />"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="productId" value="${p.id}"><input type="hidden" name="quantity" value="1"><button>Thêm giỏ hàng</button></form></c:if><c:if test="${p.stock_quantity == 0}"><small>Đã hết hàng</small></c:if><form method="post" action="<c:url value='/messages/start' />"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="productId" value="${p.id}"><button class="secondary">✉ Chat với người bán</button></form></c:otherwise></c:choose></div></td></c:forEach></tr></tbody></table></div>
<p class="condition-note">Thông tin do người bán khai báo. Điểm người bán là điểm chung từ các đánh giá giao dịch công khai đã hoàn thành; chưa có thang điểm người bán độc lập. Không suy ra chất lượng từ giá thấp nhất.</p>
</c:otherwise></c:choose>
<%@ include file="../layouts/shop-end.jspf" %>
