<%@ page pageEncoding="UTF-8" %>
<%@ include file="../layouts/shop-start.jspf" %>
<p><a href="<c:url value='/products' />">← Xem sản phẩm khác</a></p><div class="detail-grid"><div class="gallery"><c:choose><c:when test="${empty images}"><img class="gallery-main" src="<c:url value='/assets/images/product-placeholder.svg' />" alt="Người bán chưa thêm ảnh"></c:when><c:otherwise><c:url var="mainImage" value="/media/product"><c:param name="asset" value="${images[0].asset_id}" /></c:url><a class="gallery-enlarge" href="${mainImage}" aria-label="Xem ảnh sản phẩm lớn"><img class="gallery-main" src="${mainImage}" alt="<c:out value='${product.title}' />"></a><div class="gallery-thumbs"><c:forEach var="image" items="${images}" varStatus="imageStatus"><c:url var="imageUrl" value="/media/product"><c:param name="asset" value="${image.asset_id}" /></c:url><a data-gallery-image href="${imageUrl}" ${imageStatus.first ? 'aria-current="true"' : ''} aria-label="Xem ảnh ${imageStatus.count}"><img src="${imageUrl}" alt="Ảnh sản phẩm ${imageStatus.count}"></a></c:forEach></div></c:otherwise></c:choose></div>
<section class="product-info"><button type="button" class="compare-toggle" data-compare-id="${product.id}" data-compare-category="${product.category_id}" aria-pressed="false">⇄ So sánh</button><p class="eyebrow"><c:out value="${product.category_name}" /></p><h1><c:out value="${product.title}" /></h1><p class="price"><fmt:formatNumber value="${product.price}" pattern="#,##0" /> ₫</p><p>Tình trạng: <c:out value="${labels[product.condition_code]}" /> · Còn <c:out value="${product.stock_quantity}" /> sản phẩm</p><div class="seller-box"><h2>Thông tin người bán</h2><p>Người bán: <strong><c:out value="${product.seller_name}" /></strong></p><p>Liên hệ: <c:out value="${product.seller_contact}" default="Chưa cung cấp liên hệ công khai" /></p></div>
<c:if test="${empty currentUser or currentUser.id != product.seller_id}"><div class="chat-seller-action"><c:choose><c:when test="${empty currentUser}"><a class="button" href="<c:url value='/messages/start'><c:param name='productId' value='${product.id}' /></c:url>">✉ Chat với người bán</a></c:when><c:otherwise><form method="post" action="<c:url value='/messages/start' />"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="productId" value="${product.id}"><button>✉ Chat với người bán</button></form></c:otherwise></c:choose></div></c:if>
<c:choose><c:when test="${product.stock_quantity == 0}"><p class="notice">Sản phẩm đã hết hàng.</p></c:when><c:when test="${empty currentUser}"><a class="button" href="<c:url value='/login' />">Đăng nhập để mua</a></c:when><c:when test="${currentUser.id == product.seller_id}"><p>Đây là sản phẩm của bạn.</p></c:when><c:otherwise><form method="post" action="<c:url value='/cart/add' />" class="account-form"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="productId" value="${product.id}"><label>Số lượng<input name="quantity" type="number" min="1" max="${product.stock_quantity > 999 ? 999 : product.stock_quantity}" value="1" required></label><button>Thêm vào giỏ hàng</button></form></c:otherwise></c:choose></section></div><section><h2>Mô tả sản phẩm</h2><p class="preserve"><c:out value="${product.description}" /></p></section>
<%@ include file="condition.jspf" %>
<%@ include file="reviews.jspf" %>
<%@ include file="../layouts/shop-end.jspf" %>
