<%@ page pageEncoding="UTF-8" %>
<%@ include file="../layouts/shop-start.jspf" %>
<div class="page-heading"><div><p class="eyebrow">Khám phá từ cộng đồng</p><h1>Tìm sản phẩm</h1><p class="muted">Chọn món phù hợp với nhu cầu và ngân sách của bạn.</p></div></div><form method="get" action="<c:url value='/products' />" class="filter-bar">
<label>Từ khóa<input name="keyword" maxlength="100" value="<c:out value='${param.keyword}' />"></label>
<label>Danh mục<select name="category"><option value="0">Tất cả</option><c:forEach var="category" items="${categories}"><option value="${category.id}" ${param.category == category.id ? 'selected' : ''}><c:out value="${category.name}" /></option></c:forEach></select></label>
<label>Giá từ<input name="min" type="number" min="0" value="<c:out value='${param.min}' />"></label><label>Đến<input name="max" type="number" min="0" value="<c:out value='${param.max}' />"></label>
<label>Tình trạng<select name="condition"><option value="">Tất cả</option><c:forEach var="condition" items="${['NEW','LIKE_NEW','USED']}"><option value="${condition}" ${param.condition == condition ? 'selected' : ''}><c:out value="${labels[condition]}" /></option></c:forEach></select></label><button>Lọc sản phẩm</button><a class="button secondary" href="<c:url value='/products' />">Xóa lọc</a></form>
<div class="results-meta"><span><strong>${resultCount}</strong> sản phẩm phù hợp<c:if test="${not empty param.keyword}"> với “<c:out value="${param.keyword}" />”</c:if></span><span>Mới đăng trước</span></div>
<%@ include file="cards.jspf" %>
<div class="pagination"><c:if test="${page > 1}"><c:url var="previous" value="/products"><c:param name="page" value="${page-1}" /><c:param name="keyword" value="${param.keyword}" /><c:param name="category" value="${param.category}" /><c:param name="min" value="${param.min}" /><c:param name="max" value="${param.max}" /><c:param name="condition" value="${param.condition}" /></c:url><a href="${previous}">← Trang trước</a></c:if><span>Trang <c:out value="${page}" /> / <c:out value="${pages}" /></span><c:if test="${page < pages}"><c:url var="next" value="/products"><c:param name="page" value="${page+1}" /><c:param name="keyword" value="${param.keyword}" /><c:param name="category" value="${param.category}" /><c:param name="min" value="${param.min}" /><c:param name="max" value="${param.max}" /><c:param name="condition" value="${param.condition}" /></c:url><a href="${next}">Trang sau →</a></c:if></div>
<%@ include file="../layouts/shop-end.jspf" %>
