<%@ page pageEncoding="UTF-8" %>
<%@ include file="../layouts/shop-start.jspf" %>
<div class="page-heading"><div><p class="eyebrow">Thông tin giao dịch</p><h1>Đơn <c:out value="${order.order_code}" /></h1></div><span class="badge" data-status="${order.status}">${labels[order.status]}</span></div>
<c:if test="${orderView == 'buyer'}"><section>
    <c:choose><c:when test="${empty complaint}"><a href="<c:url value='/buyer/complaints/new'><c:param name='orderId' value='${order.id}' /></c:url>">Gửi khiếu nại</a></c:when><c:otherwise><a href="<c:url value='/buyer/complaints/detail'><c:param name='id' value='${complaint.id}' /></c:url>">Xem khiếu nại — ${feedbackLabels[complaint.status]}</a></c:otherwise></c:choose>
    <c:if test="${completionBlocked and order.status == 'DELIVERED'}"><p class="notice">Đơn đang có khiếu nại chưa xử lý xong. Bạn có thể xác nhận nhận hàng sau khi hồ sơ đã xử lý và thanh toán hợp lệ.</p></c:if>
</section></c:if>
<c:if test="${orderView == 'admin' and not empty complaint}"><section><a href="<c:url value='/admin/complaints/detail'><c:param name='id' value='${complaint.id}' /></c:url>">Xử lý khiếu nại liên quan — ${feedbackLabels[complaint.status]}</a></section></c:if>
<section><a href="<c:url value='${orderBase}' />">← Danh sách đơn</a><h2>Chi tiết đơn hàng</h2><p>Mã đơn: <c:out value="${order.order_code}" /></p><p><span class="badge" data-status="${order.status}">${labels[order.status]}</span> <span class="badge" data-status="${payment.status}">${labels[payment.status]}</span></p>
<div class="detail-grid"><div><h2>Giao nhận</h2><p><c:out value="${order.recipient_name}" /> · <c:out value="${order.recipient_phone}" /><br><c:out value="${order.shipping_address}" /></p><p>Người mua: <c:out value="${order.buyer_name_snapshot}" /><br>Người bán: <c:out value="${order.seller_name_snapshot}" /><br>Liên hệ người bán: <c:out value="${order.seller_contact_snapshot}" default="Chưa cung cấp" /></p></div><div><h2>Thanh toán</h2><p>${labels[payment.method]}</p><p>Tổng tiền: <strong class="price"><fmt:formatNumber value="${order.grand_total}" maxFractionDigits="0" /> đ</strong><br>Phí giao hàng: 0 đ</p><small>${payment.method == 'VNPAY_SANDBOX' ? 'VNPAY Sandbox – môi trường thử nghiệm. Dùng thẻ thử, không chuyển tiền thật.' : 'Thanh toán demo phục vụ đồ án.'}</small><c:if test="${payment.status == 'REFUND_PENDING'}"><p class="notice">Chờ xử lý hoàn tiền. Chưa thực hiện hoàn tiền qua VNPAY.</p></c:if></div></div>
<%@ include file="snapshot-items.jspf" %>
<c:if test="${canVnpay}"><form method="post" action="<c:url value='/payments/vnpay/create' />" data-payment-submit="Đang chuyển sang VNPAY…"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="orderId" value="${order.id}"><button>Thanh toán VNPAY Sandbox</button></form></c:if>
<c:if test="${not empty actions}"><h2>Thao tác với đơn</h2><div class="action-grid"><c:forEach items="${actions}" var="action"><form method="post" action="<c:url value='${orderBase}/action' />" class="action-card"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="id" value="${order.id}"><input type="hidden" name="action" value="${action}"><c:if test="${action == 'CANCEL' or orderView == 'admin'}"><label>Lý do <input name="reason" required maxlength="500"></label></c:if><button class="${action == 'CANCEL' ? 'secondary' : ''}">${labels[action]}</button></form></c:forEach></div></c:if>
</section><div class="detail-grid"><section><h2>Lịch sử đơn hàng</h2><ol class="timeline"><c:forEach items="${history}" var="event"><li><strong>${labels[event.to_status]}</strong><p><c:out value="${event.reason}" /></p><small><c:out value="${event.created_at}" /> · ${event.actor_role_snapshot == 'ADMIN' ? 'Quản trị viên' : 'Thành viên'}</small></li></c:forEach></ol></section><section><h2>Lịch sử thanh toán</h2><ol class="timeline"><c:forEach items="${paymentHistory}" var="event"><li><strong>${labels[event.to_status]}</strong><p><c:out value="${event.note}" /></p><small><c:out value="${event.created_at}" /></small></li></c:forEach></ol></section></div>
<%@ include file="../payments/attempts.jspf" %>
<%@ include file="../layouts/shop-end.jspf" %>
