<%@ page pageEncoding="UTF-8" %><%@ include file="../layouts/shop-start.jspf" %><%@ include file="tags.jspf" %>
<div class="verification-heading"><span class="verification-emblem"><svg class="icon" aria-hidden="true"><use href="#i-shield" /></svg></span><div><p class="eyebrow">Bắt đầu bán hàng cùng TraoTay</p><h1>Xác minh hồ sơ người bán</h1><p>Chỉ một lần cho tài khoản. Mua hàng, chat và giao dịch hiện có vẫn hoạt động.</p></div></div>
<ol class="verification-steps" aria-label="Tiến trình xác minh"><li class="${empty submission ? 'is-current' : 'is-done'}"><b>1</b>Tải giấy tờ</li><li class="${submission.status == 'DRAFT' ? 'is-current' : verificationStatus == 'PENDING' or verificationStatus == 'APPROVED' ? 'is-done' : ''}"><b>2</b>Kiểm tra thông tin</li><li class="${verificationStatus == 'PENDING' ? 'is-current' : verificationStatus == 'APPROVED' ? 'is-done' : ''}"><b>3</b>Chờ duyệt</li><li class="${verificationStatus == 'APPROVED' ? 'is-current' : ''}"><b>4</b>Hoàn tất</li></ol>
<c:if test="${param.notice == 'required'}"><p class="notice">Cần hồ sơ người bán được duyệt trước khi đăng tin. Bắt đầu tại đây nhé!</p></c:if>
<c:if test="${param.notice == 'submitted'}"><p class="notice" role="status">Đã gửi hồ sơ. Quản trị viên sẽ đối chiếu giấy tờ và thông tin của bạn.</p></c:if>
<c:if test="${param.notice == 'purged'}"><p class="notice" role="status">Đã xóa ảnh và thông tin giấy tờ của bạn. Cần xác minh lại để đăng tin mới.</p></c:if>
<c:if test="${not empty formError}"><p class="error" role="alert"><c:out value="${formError}" /></p></c:if>
<c:if test="${not empty qrMessage}"><p class="notice" role="status"><c:out value="${qrMessage}" /></p></c:if>
<c:if test="${submission.status == 'DRAFT'}"><p><a class="button secondary" href="#verification-info">Kiểm tra thông tin &amp; gửi hồ sơ ↓</a></p></c:if><div class="verification-layout"><div>
<c:if test="${not empty submission and submission.status != 'DRAFT'}"><section class="verification-status"><div class="section-heading"><h2>Hồ sơ của bạn</h2><span class="badge" data-status="${verificationStatus}"><c:out value="${verificationLabels[verificationStatus]}" /></span></div>
<c:choose><c:when test="${verificationStatus == 'APPROVED'}"><p class="seller-approved"><svg class="icon" aria-hidden="true"><use href="#i-shield" /></svg> Đã xác minh hồ sơ</p><p>Giấy tờ trong hồ sơ đã được quản trị viên kiểm tra.</p><a class="button" href="<c:url value='/seller/products/new' />">Đăng tin ngay →</a></c:when><c:when test="${verificationStatus == 'PENDING'}"><h3>Hồ sơ đang chờ đối chiếu</h3><p>Thông tin đã gửi được giữ nguyên trong lúc chờ quyết định. Bạn vẫn có thể mua hàng và xử lý đơn cũ.</p></c:when><c:otherwise><h3>Hãy bổ sung để gửi lại</h3><p class="verification-reason"><strong>Lý do:</strong> <c:out value="${submission.rejection_reason}" /></p><p>Chọn lại giấy tờ, kiểm tra thông tin và gửi phiên bản mới ở bên dưới.</p></c:otherwise></c:choose>
<dl class="verification-dates"><c:if test="${not empty submission.submitted_at}"><dt>Đã gửi</dt><dd><c:out value="${submission.submitted_at}" /></dd></c:if><c:if test="${not empty submission.reviewed_at}"><dt>Đã xử lý</dt><dd><c:out value="${submission.reviewed_at}" /></dd></c:if></dl><c:if test="${not empty submission.reviewer_name}"><p class="muted">Quản trị viên phụ trách: <c:out value="${submission.reviewer_name}" /></p></c:if><details><summary>Xem thông tin đã gửi</summary><p>Họ tên: <c:out value="${submission.full_name}" /></p><p>Số giấy tờ: <c:out value="${submission.id_number}" /></p><c:if test="${not submission.legacy}"><p>Ngày sinh: <c:out value="${submission.birth_date}" /> · Giới tính: <c:out value="${submission.gender}" /></p><p>Nơi cư trú: <c:out value="${submission.residence}" /></p><p>Ngày cấp: <c:out value="${submission.issue_date}" /></p></c:if><p>Nguồn: <c:out value="${submission.sourceLabel}" /></p><%@ include file="images.jspf" %></details></section></c:if>
<c:if test="${submission.status == 'DRAFT'}"><section class="verification-form" id="verification-info"><h2>2. Kiểm tra và gửi hồ sơ</h2><p>Đọc QR chỉ hỗ trợ nhập liệu. Kiểm tra với hai ảnh và xác nhận thông tin trước khi gửi.</p><p class="verification-source"><strong>Nguồn thông tin:</strong> <c:out value="${submission.sourceLabel}" /></p><c:if test="${submission.legacy}"><p class="notice">Hồ sơ này được tạo ở luồng cũ. Thông tin và nguồn ban đầu vẫn được giữ. Tải đủ hai ảnh mới nếu muốn dùng QR và bổ sung sáu trường.</p></c:if><c:if test="${not submission.legacy and submission.qr_status != 'SUCCESS'}"><p class="verification-hint"><c:out value="${submission.qr_status == 'CONFLICT' ? 'Các QR có thông tin mâu thuẫn. Hãy tải lại hai mặt của cùng một căn cước.' : 'Bạn đang nhập thủ công. Quản trị viên sẽ đối chiếu đầy đủ hai ảnh trước khi quyết định.'}" /></p></c:if><%@ include file="images.jspf" %>
<form method="post" action="<c:url value='/seller/verification/submit' />" class="account-form" data-identity-form><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="id" value="${submission.id}">
<div class="form-row"><label>Số CCCD / số định danh cá nhân<input name="idNumber" inputmode="numeric" pattern="${submission.legacy ? '([0-9]{9}|[0-9]{12})' : '[0-9]{12}'}" maxlength="12" required autocomplete="off" value="<c:out value='${posted ? param.idNumber : submission.prefill_id_number}' />"></label><label>Họ và tên<input name="fullName" maxlength="120" required autocomplete="off" value="<c:out value='${posted ? param.fullName : submission.prefill_full_name}' />"></label></div>
<c:if test="${not submission.legacy}"><div class="form-row"><label>Ngày sinh<input name="birthDate" placeholder="dd/MM/yyyy" inputmode="text" maxlength="10" required value="<c:out value='${posted ? param.birthDate : submission.prefill_birth_date}' />"></label><label>Giới tính<select name="gender" required><option value="">Chọn giới tính</option><c:forEach var="g" items="${['Nam','Nữ','Khác']}"><option value="${g}" ${(posted ? param.gender : submission.prefill_gender) == g ? 'selected' : ''}>${g}</option></c:forEach></select></label></div><label>Nơi thường trú / nơi cư trú<textarea name="residence" rows="2" maxlength="500" required><c:out value="${posted ? param.residence : submission.prefill_residence}" /></textarea></label><label>Ngày cấp<input name="issueDate" placeholder="dd/MM/yyyy" inputmode="text" maxlength="10" required value="<c:out value='${posted ? param.issueDate : submission.prefill_issue_date}' />"></label></c:if>
<p class="muted">Thông tin căn cước không được công khai và không thay đổi tên hiển thị. Quản trị viên sẽ thấy những trường bạn sửa so với kết quả đọc.</p><button ${submission.qr_status == 'CONFLICT' ? 'disabled' : ''}>Xác nhận &amp; gửi hồ sơ</button></form>
<c:if test="${not submission.legacy}"><form method="post" action="<c:url value='/seller/verification/read' />#verification-info" data-verification-read><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="id" value="${submission.id}"><button class="secondary">Đọc lại QR trên hai ảnh</button><p data-verification-loading hidden role="status">Đang đọc mã QR…</p></form></c:if></section></c:if>
<c:if test="${verificationStatus != 'PENDING'}"><section class="verification-upload"><c:if test="${submission.status == 'DRAFT'}"><details data-change-documents><summary>Đổi ảnh căn cước · tải lại cả hai mặt</summary></c:if><h2>${verificationStatus == 'APPROVED' ? 'Thay đổi giấy tờ / thông tin' : '1. Tải giấy tờ của bạn'}</h2><p>Ảnh JPEG/PNG, mỗi mặt tối đa 5 MB. Chụp rõ cả 4 góc, không chỉnh sửa thông tin; ưu tiên độ phân giải từ 1280 × 720. QR có thể ở mặt trước hoặc mặt sau; chụp đủ vùng mã, tránh lóa và nhòe.</p>
<c:if test="${verificationStatus == 'APPROVED'}"><p class="notice">Tải giấy tờ mới sẽ ngừng quyền đăng tin mới và nhãn đã duyệt cho đến khi được duyệt lại. Tin cũ và các đơn đang xử lý vẫn được giữ.</p></c:if>
<form class="account-form" method="post" enctype="multipart/form-data" action="<c:url value='/seller/verification/upload' />#verification-info" data-verification-upload><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />">
<div class="verification-consent"><label><input type="checkbox" name="consent" value="true" required> Tôi đồng ý lưu hai ảnh và thông tin căn cước riêng tư để quản trị viên đối chiếu hồ sơ.</label><p>Mã QR được đọc trực tiếp trên hệ thống TraoTay. Ảnh không được gửi đến dịch vụ đọc giấy tờ bên ngoài.</p></div>
<div class="verification-upload-grid"><label class="verification-drop">Mặt trước <span class="muted">Bắt buộc · chụp rõ ảnh và mã QR</span><input type="file" name="front" accept="image/jpeg,image/png" required data-document-input><span class="verification-file-label">Chọn ảnh từ thiết bị</span><span class="muted" data-document-name>Chưa chọn ảnh</span><img data-document-preview hidden alt="Ảnh xem trước mặt trước"></label><label class="verification-drop">Mặt sau <span class="muted">Bắt buộc · QR có thể nằm ở mặt này</span><input type="file" name="back" accept="image/jpeg,image/png" required data-document-input><span class="verification-file-label">Chọn ảnh từ thiết bị</span><span class="muted" data-document-name>Chưa chọn ảnh</span><img data-document-preview hidden alt="Ảnh xem trước mặt sau"></label></div>
<button type="submit">Đọc thông tin từ QR</button><p class="verification-loading" data-verification-loading hidden role="status">Đang đọc mã QR…</p></form><c:if test="${submission.status == 'DRAFT'}"></details></c:if></section></c:if>
</div><aside class="verification-guide"><svg class="icon" aria-hidden="true"><use href="#i-shield" /></svg><h2>Riêng tư từ bước đầu</h2><p>Ảnh chỉ chủ hồ sơ và quản trị viên phụ trách được xem. Không hiển thị số giấy tờ cho người mua.</p><h3>Nhận nhãn sau khi duyệt</h3><p>“Đã xác minh hồ sơ” nghĩa là giấy tờ đã được quản trị viên kiểm tra. Đây không phải xác thực chính thức với cơ quan nhà nước hay bảo đảm giao dịch không có rủi ro. Đọc QR không chứng minh người tải ảnh là chủ căn cước.</p><h3>Vẫn là một tài khoản</h3><p>Bạn vừa mua vừa bán. Xác minh chỉ cần cho đăng tin; các giao dịch hiện có vẫn tiếp tục.</p><a href="<c:url value='/seller/products' />">Tin đăng của tôi →</a></aside></div>
<c:if test="${not empty submission}"><details class="verification-purge"><summary>Xóa giấy tờ đã gửi</summary><p>Xóa ảnh và thông tin cá nhân trong tất cả phiên bản hồ sơ. Quyền đăng tin mới và nhãn đã duyệt sẽ ngừng; sản phẩm, đơn hàng và lịch sử quyết định vẫn giữ.</p><form method="post" action="<c:url value='/seller/verification/purge' />"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><label><input type="checkbox" name="confirm" value="true" required> Tôi xác nhận xóa giấy tờ và cần duyệt lại nếu đăng tin mới.</label><button class="danger">Xóa giấy tờ của tôi</button></form></details></c:if>
<%@ include file="../layouts/shop-end.jspf" %>
